import { Category, Product } from "./types";

export const categories: Category[] = [
  {
    id: 1,
    name: "Skincare",
    description: "Premium skincare products",
    image_url:
      "https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg?w=200&h=200&fit=crop",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Supplements",
    description: "Health supplements",
    image_url:
      "https://images.pexels.com/photos/3622613/pexels-photo-3622613.jpeg?w=200&h=200&fit=crop",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Wellness",
    description: "Wellness products",
    image_url:
      "https://images.pexels.com/photos/3807513/pexels-photo-3807513.jpeg?w=200&h=200&fit=crop",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Beauty",
    description: "Beauty essentials",
    image_url:
      "https://images.pexels.com/photos/3760790/pexels-photo-3760790.jpeg?w=200&h=200&fit=crop",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Hair Care",
    description: "Hair care solutions",
    image_url:
      "https://images.pexels.com/photos/3775221/pexels-photo-3775221.jpeg?w=200&h=200&fit=crop",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Fitness",
    description: "Fitness products",
    image_url:
      "https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg?w=200&h=200&fit=crop",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const products: Product[] = [
  {
    id: 1,
    name: "Hydrating Facial Serum",
    description:
      "Intensive hydration serum with hyaluronic acid for plump, glowing skin",
    price: 45.99,
    original_price: 65.0,
    image_url:
      "https://apia.ma/wp-content/uploads/2023/12/Huile-dargan-125ml-scaled.jpg",
    category_id: 1,
    category_name: "Skincare",
    stock_quantity: 150,
    is_featured: 1,
    rating: 4.8,
    review_count: 234,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Vitamin C Brightening Mask",
    description: "Radiance-boosting mask with vitamin C and botanical extracts",
    price: 35.5,
    original_price: null,
    image_url:
      "https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg?w=400",
    category_id: 1,
    category_name: "Skincare",
    stock_quantity: 200,
    is_featured: 1,
    rating: 4.6,
    review_count: 156,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Collagen Peptides",
    description: "Premium collagen supplement for skin, hair, and joint health",
    price: 52.0,
    original_price: 70.0,
    image_url:
      "https://images.pexels.com/photos/3807513/pexels-photo-3807513.jpeg?w=400",
    category_id: 2,
    category_name: "Supplements",
    stock_quantity: 120,
    is_featured: 1,
    rating: 4.7,
    review_count: 289,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Omega-3 Fish Oil",
    description: "High-potency omega-3 for heart and brain health",
    price: 29.99,
    original_price: null,
    image_url:
      "https://apia.ma/wp-content/uploads/2023/12/Huile-dargan-125ml-scaled.jpg",
    category_id: 2,
    category_name: "Supplements",
    stock_quantity: 300,
    is_featured: 0,
    rating: 4.5,
    review_count: 178,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Silk Pillowcase",
    description: "Luxurious silk pillowcase for hair and skin health",
    price: 38.0,
    original_price: 55.0,
    image_url:
      "https://images.pexels.com/photos/3775221/pexels-photo-3775221.jpeg?w=400",
    category_id: 5,
    category_name: "Hair Care",
    stock_quantity: 85,
    is_featured: 1,
    rating: 4.9,
    review_count: 312,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Argan Oil Hair Treatment",
    description: "Nourishing argan oil for deep conditioning and shine",
    price: 28.5,
    original_price: null,
    image_url:
      "https://images.pexels.com/photos/3760790/pexels-photo-3760790.jpeg?w=400",
    category_id: 5,
    category_name: "Hair Care",
    stock_quantity: 160,
    is_featured: 0,
    rating: 4.7,
    review_count: 145,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Yoga Mat Premium",
    description: "Non-slip yoga mat with carrying strap and alignment markers",
    price: 59.99,
    original_price: 79.99,
    image_url:
      "https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg?w=400",
    category_id: 6,
    category_name: "Fitness",
    stock_quantity: 75,
    is_featured: 1,
    rating: 4.8,
    review_count: 267,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 8,
    name: "Resistance Bands Set",
    description: "Complete set of 5 resistance bands for full-body workouts",
    price: 24.99,
    original_price: null,
    image_url:
      "https://apia.ma/wp-content/uploads/2023/12/Huile-dargan-125ml-scaled.jpg",
    category_id: 6,
    category_name: "Fitness",
    stock_quantity: 200,
    is_featured: 0,
    rating: 4.6,
    review_count: 189,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 9,
    name: "Anti-Aging Eye Cream",
    description: "Potent eye cream targeting wrinkles and dark circles",
    price: 55.0,
    original_price: 75.0,
    image_url:
      "https://images.pexels.com/photos/3807513/pexels-photo-3807513.jpeg?w=400",
    category_id: 1,
    category_name: "Skincare",
    stock_quantity: 110,
    is_featured: 0,
    rating: 4.7,
    review_count: 203,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 10,
    name: "Probiotics Complex",
    description: "Advanced probiotic formula for digestive and immune health",
    price: 42.0,
    original_price: 60.0,
    image_url:
      "https://images.pexels.com/photos/3760790/pexels-photo-3760790.jpeg?w=400",
    category_id: 2,
    category_name: "Supplements",
    stock_quantity: 140,
    is_featured: 1,
    rating: 4.8,
    review_count: 224,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 11,
    name: "Luxury Face Cleanser",
    description:
      "Gentle yet effective facial cleanser with natural ingredients",
    price: 32.0,
    original_price: 45.0,
    image_url:
      "https://images.pexels.com/photos/3775221/pexels-photo-3775221.jpeg?w=400",
    category_id: 1,
    category_name: "Skincare",
    stock_quantity: 180,
    is_featured: 0,
    rating: 4.5,
    review_count: 167,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 12,
    name: "Water Bottle Infuser",
    description: "Elegant bottle for infusing water with fruits and herbs",
    price: 19.99,
    original_price: null,
    image_url:
      "https://apia.ma/wp-content/uploads/2023/12/Huile-dargan-125ml-scaled.jpg",
    category_id: 3,
    category_name: "Wellness",
    stock_quantity: 250,
    is_featured: 0,
    rating: 4.4,
    review_count: 98,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
